# name: Browserstack Automated Regression Tests
# on:
#   push:
#     branches: [ main, master ]
#     paths:
#       - 'Zadanie_6/**'
#   pull_request:
#     branches: [ main, master ]
#     paths:
#       - 'Zadanie_6/**'
#   workflow_dispatch:
# jobs:
#   regression-tests:
#     name: Run Cypress on Browserstack
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4
#       - name: Set up Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20
#           cache: 'npm'
#           cache-dependency-path: Zadanie_6/package-lock.json
#       - name: Install dependencies
#         run: npm ci
#         working-directory: Zadanie_6

#       - name: Run Browserstack tests
#         run: npm run test:browserstack
#         working-directory: Zadanie_6
#         env:
#           BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
#           BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}